# cf_edge_pick.ps1 - pick the fastest reachable Cloudflare anycast edge IP for
# proxied hostnames from a mainland-China client and pin it in the hosts file.
#
# Why: the CF free plan has no mainland PoP, and default DNS often lands on a
# congested overseas edge.  Any CF anycast edge serves any proxied hostname
# (SNI routing), so probing a spread of edge IPs and pinning the best one in
# the hosts file typically cuts TLS handshake time 30-60%.  Pure client-side,
# reversible with -Restore, keeps Cloudflare Access auth fully intact.
#
# Usage (admin for the hosts write):
#   powershell -File cf_edge_pick.ps1                          # probe + pin
#   powershell -File cf_edge_pick.ps1 -DryRun                  # probe only
#   powershell -File cf_edge_pick.ps1 -Restore                 # unpin
#   powershell -File cf_edge_pick.ps1 -Hostname api.example.com
param(
    [string[]]$Hostname = @("api.qqking.top", "pc.qqking.top"),
    [string]$HostsPath = "$env:SystemRoot\System32\drivers\etc\hosts",
    [switch]$Restore,
    [switch]$DryRun,
    [int]$ProbeTimeoutMs = 1200,
    [int]$Runs = 3
)
$ErrorActionPreference = 'Continue'
$BEGIN = '# BEGIN local-llm-stack cf-edge (generated by cf_edge_pick.ps1)'
$END = '# END local-llm-stack cf-edge'

# A spread across Cloudflare anycast ranges; any of these serves any proxied
# hostname.  Includes the 1.1.1.1 anycast pair (same edge network).
$probeIps = @(
    '1.1.1.1', '1.0.0.1',
    '104.16.1.1', '104.17.1.1', '104.18.1.1', '104.19.1.1', '104.20.1.1',
    '104.21.1.1', '104.22.1.1', '104.24.1.1', '104.25.1.1', '104.26.1.1',
    '104.27.1.1', '172.64.1.1', '172.65.1.1', '172.66.1.1', '172.67.1.1',
    '162.159.1.1', '162.159.8.1', '162.159.16.1',
    '188.114.96.1', '188.114.97.1',
    '108.162.192.1', '108.162.224.1'
)

function Test-Edge([string]$ip, [string]$sni, [int]$timeoutMs) {
    $tcp = New-Object Net.Sockets.TcpClient
    try {
        $sw = [Diagnostics.Stopwatch]::StartNew()
        $iar = $tcp.BeginConnect($ip, 443, $null, $null)
        if (-not $iar.AsyncWaitHandle.WaitOne($timeoutMs)) { return $null }
        $tcp.EndConnect($iar)
        $tcpMs = [math]::Round($sw.Elapsed.TotalMilliseconds)
        $ssl = New-Object Net.Security.SslStream($tcp.GetStream(), $false, { $true })
        $t2 = [Diagnostics.Stopwatch]::StartNew()
        $ssl.AuthenticateAsClient($sni)
        $tlsMs = [math]::Round($t2.Elapsed.TotalMilliseconds)
        $ssl.Dispose()
        return [pscustomobject]@{ ip = $ip; tcp = $tcpMs; tls = $tlsMs; total = ($tcpMs + $tlsMs) }
    } catch { return $null } finally { $tcp.Close() }
}

if ($Restore) {
    $kept = Get-Content $HostsPath | Where-Object { $_ -ne $BEGIN -and $_ -ne $END -and $_ -notmatch '^# local-llm-stack cf-edge' }
    Set-Content -Path $HostsPath -Value $kept -Encoding ASCII
    ipconfig /flushdns | Out-Null
    "hosts block removed; DNS cache flushed"
    return
}

$sni = $Hostname[0]
"probing $($probeIps.Count) edge IPs against SNI $sni ($Runs runs each)..."
$results = foreach ($ip in $probeIps) {
    $best = $null
    1..$Runs | ForEach-Object {
        $r = Test-Edge $ip $sni $ProbeTimeoutMs
        if ($r -and (-not $best -or $r.total -lt $best.total)) { $best = $r }
    }
    if ($best) { $best }
}
if (-not $results) { "all probes failed - network offline?"; exit 1 }

$ranked = $results | Sort-Object total
"ip            tcp   tls  total"
$ranked | Select-Object -First 8 | ForEach-Object { "{0,-14} {1,4}  {2,4}  {3,5}" -f $_.ip, $_.tcp, $_.tls, $_.total }
$best = $ranked[0]
"best: $($best.ip) ($($best.total)ms handshake)"

if ($DryRun) { "dry run - hosts untouched"; return }

$isAdmin = ([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()
           ).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
if (-not $isAdmin) { "not admin - cannot write hosts; re-run elevated"; exit 1 }

$out = New-Object System.Collections.Generic.List[string]
$inBlock = $false
foreach ($l in (Get-Content $HostsPath)) {
    if ($l -eq $BEGIN) { $inBlock = $true; continue }
    if ($l -eq $END) { $inBlock = $false; continue }
    if (-not $inBlock) { $out.Add($l) }
}
$out.Add($BEGIN)
foreach ($h in $Hostname) { $out.Add("$($best.ip) $h") }
$out.Add($END)
Set-Content -Path $HostsPath -Value $out -Encoding ASCII
ipconfig /flushdns | Out-Null
"hosts pinned $($best.ip) -> $($Hostname -join ', '); DNS cache flushed"
